"""add before and after clumns in poland.

Revision ID: 08c220bce0e5
Revises: 687b8fb8d095
Create Date: 2024-04-02 17:59:09.577186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c220bce0e5'
down_revision = '687b8fb8d095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Poland_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_dis_bf_010323', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('min_dis_af_010323', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('min_pet_bf_010323', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('min_pet_af_010323', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Poland_registrations', schema=None) as batch_op:
        batch_op.drop_column('min_pet_af_010323')
        batch_op.drop_column('min_pet_bf_010323')
        batch_op.drop_column('min_dis_af_010323')
        batch_op.drop_column('min_dis_bf_010323')

    # ### end Alembic commands ###
