"""replace norway reg with portugal

Revision ID: 3a93c207cc9a
Revises: 97afd0c2d124
Create Date: 2024-03-22 11:23:12.412572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a93c207cc9a'
down_revision = '97afd0c2d124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Norway_registrations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Norway_registrations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('country', sa.VARCHAR(length=50), nullable=True),
    sa.Column('registration_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('minimum_diesel', sa.VARCHAR(length=50), nullable=True),
    sa.Column('minimum_petrol', sa.VARCHAR(length=50), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
