"""update car table

Revision ID: 4573c03ad588
Revises: ab94c4baaee4
Create Date: 2024-03-16 11:37:06.915912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4573c03ad588'
down_revision = 'ab94c4baaee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('denmark_registrations', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('france_registrations', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('germany_registrations', sa.String(length=50), nullable=True))
        batch_op.drop_column('france_registration')
        batch_op.drop_column('germany_registration')
        batch_op.drop_column('denmark_registration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('denmark_registration', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('germany_registration', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('france_registration', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('germany_registrations')
        batch_op.drop_column('france_registrations')
        batch_op.drop_column('denmark_registrations')

    # ### end Alembic commands ###
