"""add resume column to Registrations abstract class

Revision ID: 687b8fb8d095
Revises: c4171f0e1c2d
Create Date: 2024-04-01 11:16:48.665035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687b8fb8d095'
down_revision = 'c4171f0e1c2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Belgium_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.Text(), nullable=True))

    with op.batch_alter_table('Bulgaria_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.Text(), nullable=True))

    with op.batch_alter_table('Denmark_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.Text(), nullable=True))

    with op.batch_alter_table('France_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.Text(), nullable=True))

    with op.batch_alter_table('Germany_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.Text(), nullable=True))

    with op.batch_alter_table('Greece_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.Text(), nullable=True))

    with op.batch_alter_table('Netherlands_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.Text(), nullable=True))

    with op.batch_alter_table('Poland_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.Text(), nullable=True))

    with op.batch_alter_table('Portugal_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.Text(), nullable=True))

    with op.batch_alter_table('Spain_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.Text(), nullable=True))

    with op.batch_alter_table('UnitedKingdom_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UnitedKingdom_registrations', schema=None) as batch_op:
        batch_op.drop_column('result')

    with op.batch_alter_table('Spain_registrations', schema=None) as batch_op:
        batch_op.drop_column('result')

    with op.batch_alter_table('Portugal_registrations', schema=None) as batch_op:
        batch_op.drop_column('result')

    with op.batch_alter_table('Poland_registrations', schema=None) as batch_op:
        batch_op.drop_column('result')

    with op.batch_alter_table('Netherlands_registrations', schema=None) as batch_op:
        batch_op.drop_column('result')

    with op.batch_alter_table('Greece_registrations', schema=None) as batch_op:
        batch_op.drop_column('result')

    with op.batch_alter_table('Germany_registrations', schema=None) as batch_op:
        batch_op.drop_column('result')

    with op.batch_alter_table('France_registrations', schema=None) as batch_op:
        batch_op.drop_column('result')

    with op.batch_alter_table('Denmark_registrations', schema=None) as batch_op:
        batch_op.drop_column('result')

    with op.batch_alter_table('Bulgaria_registrations', schema=None) as batch_op:
        batch_op.drop_column('result')

    with op.batch_alter_table('Belgium_registrations', schema=None) as batch_op:
        batch_op.drop_column('result')

    # ### end Alembic commands ###
