"""add dpf field to Car table

Revision ID: 6e36612bad54
Revises: 9807bf18fe05
Create Date: 2024-06-01 08:35:59.941467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e36612bad54'
down_revision = '9807bf18fe05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dpf', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('dpf')

    # ### end Alembic commands ###
