"""add city_alias

Revision ID: 6f58e932db76
Revises: 6e36612bad54
Create Date: 2024-06-27 08:49:49.297226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f58e932db76'
down_revision = '6e36612bad54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_alias', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zone', schema=None) as batch_op:
        batch_op.drop_column('city_alias')

    # ### end Alembic commands ###
