"""add country column to temp table

Revision ID: 892f474fc82f
Revises: e4306e72cb66
Create Date: 2024-03-23 16:43:32.704703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892f474fc82f'
down_revision = 'e4306e72cb66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zone_temporary_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zone_temporary_data', schema=None) as batch_op:
        batch_op.drop_column('country')

    # ### end Alembic commands ###
