"""add exception country

Revision ID: 97afd0c2d124
Revises: b37209639f16
Create Date: 2024-03-19 12:47:04.400782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97afd0c2d124'
down_revision = 'b37209639f16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Belgium_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exception_country', sa.String(length=50), nullable=True))

    with op.batch_alter_table('Denmark_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exception_country', sa.String(length=50), nullable=True))

    with op.batch_alter_table('Netherlands_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exception_country', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Netherlands_registrations', schema=None) as batch_op:
        batch_op.drop_column('exception_country')

    with op.batch_alter_table('Denmark_registrations', schema=None) as batch_op:
        batch_op.drop_column('exception_country')

    with op.batch_alter_table('Belgium_registrations', schema=None) as batch_op:
        batch_op.drop_column('exception_country')

    # ### end Alembic commands ###
