"""add destinations_text column to SavedRoute

Revision ID: 9807bf18fe05
Revises: 08c220bce0e5
Create Date: 2024-04-05 10:18:27.603948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9807bf18fe05'
down_revision = '08c220bce0e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destinations_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_routes', schema=None) as batch_op:
        batch_op.drop_column('destinations_text')

    # ### end Alembic commands ###
