"""Update Car structure

Revision ID: ab94c4baaee4
Revises: 26a51efb26af
Create Date: 2024-03-16 11:08:24.753908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab94c4baaee4'
down_revision = '26a51efb26af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('belgium_registrations', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bulgaria_registrations', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('denmark_registration', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('france_registration', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('germany_registration', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('greece_registrations', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('netherlands_registrations', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('norway_registrations', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('poland_registrations', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('spain_registrations', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('united_kingdom_registrations', sa.String(length=50), nullable=True))
        batch_op.drop_column('e_badge')
        batch_op.drop_column('german_environment_class')
        batch_op.drop_column('certificat_air_class')
        batch_op.drop_column('stick_air_badge')
        batch_op.drop_column('registrations')
        batch_op.drop_column('distintivo_ambiental_badge')
        batch_op.drop_column('austrian_badge')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('austrian_badge', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('distintivo_ambiental_badge', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('registrations', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('stick_air_badge', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('certificat_air_class', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('german_environment_class', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('e_badge', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('united_kingdom_registrations')
        batch_op.drop_column('spain_registrations')
        batch_op.drop_column('poland_registrations')
        batch_op.drop_column('norway_registrations')
        batch_op.drop_column('netherlands_registrations')
        batch_op.drop_column('greece_registrations')
        batch_op.drop_column('germany_registration')
        batch_op.drop_column('france_registration')
        batch_op.drop_column('denmark_registration')
        batch_op.drop_column('bulgaria_registrations')
        batch_op.drop_column('belgium_registrations')

    # ### end Alembic commands ###
