"""add name columns and dpf for germany 

Revision ID: b37209639f16
Revises: 0c0c2f3ca821
Create Date: 2024-03-18 12:47:24.603387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b37209639f16'
down_revision = '0c0c2f3ca821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('France_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))

    with op.batch_alter_table('Germany_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minimum_diesel_wdpf', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('minimum_petrol_wdpf', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))

    with op.batch_alter_table('Spain_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Spain_registrations', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('Germany_registrations', schema=None) as batch_op:
        batch_op.drop_column('name')
        batch_op.drop_column('minimum_petrol_wdpf')
        batch_op.drop_column('minimum_diesel_wdpf')

    with op.batch_alter_table('France_registrations', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
