"""add start_time and end_time to tp lez

Revision ID: e4306e72cb66
Revises: 3a93c207cc9a
Create Date: 2024-03-23 11:22:26.423603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4306e72cb66'
down_revision = '3a93c207cc9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zone_temporary_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tp_lez_start', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tp_lez_end', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zone_temporary_data', schema=None) as batch_op:
        batch_op.drop_column('tp_lez_end')
        batch_op.drop_column('tp_lez_start')

    # ### end Alembic commands ###
